# ./Dockerfile.production
FROM golang as builder
WORKDIR /robin
COPY . .
RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux go build -a -tags robin -o build/robin ./cmd/api

FROM alpine
COPY --from=builder /robin/build/robin app
ENV PORT 5001
EXPOSE 5001
ENTRYPOINT ["/app"]